@BASE_URL=http://localhost:3000
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6InVzZXIiLCJpYXQiOjE3ODI1NzQzNzR9.R3TYWMfwRnyFXVQ2If1p8JYmJgbjAM4Eyq9NmnqPjPQ
@ORDER_ID=1


### ==================================================
### TC-ORDERHISTORY-012
### Kiểm tra lấy lịch sử đơn hàng khi không có token
### Expected: 401 Unauthorized
### ==================================================

GET {{BASE_URL}}/api/orders/my-orders



### ==================================================
### TC-ORDERHISTORY-013
### Kiểm tra user chỉ xem được đơn hàng của chính mình
### User A token
### Expected: Chỉ trả order của User A
### ==================================================

GET {{BASE_URL}}/api/orders/my-orders
Authorization: Bearer {{TOKEN}}



### ==================================================
### TC-ORDERHISTORY-014
### Kiểm tra xem thông tin đơn hàng người khác mà không cần token
### Expected: 403 hoặc 404
### ==================================================

GET {{BASE_URL}}/api/orders/{{ORDER_ID}}




### ==================================================
### Kiểm tra người dùng có role `user` không thể 
### truy cập API/trang Quản lý Người dùng của Admin.
### Expected: 403 hoặc 404
### ==================================================
GET {{BASE_URL}}/api/admin/users
Authorization: Bearer {{TOKEN}}




### ==================================================
### Xóa người dùng với với token của user thường
### Expected: 403 Forbidden
### ==================================================
DELETE {{BASE_URL}}/api/admin/users/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6InVzZXIiLCJpYXQiOjE3ODI1NzQzNzR9.R3TYWMfwRnyFXVQ2If1p8JYmJgbjAM4Eyq9NmnqPjPQ