#!/usr/bin/env python3
"""
generate_jmx.py - Generates Apache JMeter 5.6.3 XML test plans from a JSON workflow configuration.
"""

import argparse
import json
import os
import sys
import xml.etree.ElementTree as ET
from xml.dom import minidom

def build_jmx_from_config(config_path, scenario="Load", out_path=None):
    with open(config_path, 'r', encoding='utf-8') as f:
        cfg = json.load(f)

    meta = cfg.get("meta", {})
    target = cfg.get("target", {})
    workflow = cfg.get("workflow", [])
    load_profiles = cfg.get("load_profiles", {})
    data_cfg = cfg.get("data", {})

    student_id = meta.get("student_id", "23127207")
    scenario_clean = scenario.capitalize()
    testplan_name = f"{student_id}_{scenario_clean}_20260814"

    if out_path is None:
        out_path = f"{testplan_name}.jmx"

    # Profile settings
    profile = load_profiles.get(scenario_clean, {})
    if not profile:
        profile = {"threads": 50, "ramp_up_sec": 60, "duration_sec": 300, "listener": "AggregateReport"}

    listener_type = profile.get("listener", "AggregateReport")

    # Construct XML
    root = ET.Element("jmeterTestPlan", version="1.2", properties="5.0", jmeter="5.6.3")
    main_hash = ET.SubElement(root, "hashTree")

    # TestPlan element
    tp = ET.SubElement(main_hash, "TestPlan", guiclass="TestPlanGui", testclass="TestPlan", testname=testplan_name, enabled="true")
    ET.SubElement(tp, "stringProp", name="TestPlan.comments").text = f"Generated by Agent Skill for {meta.get('workflow_name', 'workflow')}"
    ET.SubElement(tp, "boolProp", name="TestPlan.functional_mode").text = "false"
    ET.SubElement(tp, "boolProp", name="TestPlan.tearDown_on_shutdown").text = "true"
    ET.SubElement(tp, "boolProp", name="TestPlan.serialize_threadgroups").text = "false"

    udv = ET.SubElement(tp, "elementProp", name="TestPlan.user_defined_variables", elementType="Arguments", guiclass="ArgumentsPanel", testclass="Arguments", testname="User Defined Variables", enabled="true")
    udv_coll = ET.SubElement(udv, "collectionProp", name="Arguments.arguments")

    for k, v in [("BASE_HOST", target.get("host", "localhost")), ("BASE_PORT", str(target.get("port", 3000))), ("PROTOCOL", target.get("protocol", "http"))]:
        arg_el = ET.SubElement(udv_coll, "elementProp", name=k, elementType="Argument")
        ET.SubElement(arg_el, "stringProp", name="Argument.name").text = k
        ET.SubElement(arg_el, "stringProp", name="Argument.value").text = v
        ET.SubElement(arg_el, "stringProp", name="Argument.metadata").text = "="

    tp_hash = ET.SubElement(main_hash, "hashTree")

    # HTTP Defaults
    defaults = ET.SubElement(tp_hash, "ConfigTestElement", guiclass="HttpDefaultsGui", testclass="ConfigTestElement", testname="HTTP Request Defaults", enabled="true")
    ET.SubElement(defaults, "stringProp", name="HTTPSampler.domain").text = "${BASE_HOST}"
    ET.SubElement(defaults, "stringProp", name="HTTPSampler.port").text = "${BASE_PORT}"
    ET.SubElement(defaults, "stringProp", name="HTTPSampler.protocol").text = "${PROTOCOL}"
    ET.SubElement(defaults, "stringProp", name="HTTPSampler.contentEncoding").text = "UTF-8"
    ET.SubElement(defaults, "stringProp", name="HTTPSampler.implementation").text = "HttpClient4"
    ET.SubElement(tp_hash, "hashTree")

    # HTTP Header Manager
    headers = ET.SubElement(tp_hash, "HeaderManager", guiclass="HeaderPanel", testclass="HeaderManager", testname="HTTP Header Manager", enabled="true")
    h_coll = ET.SubElement(headers, "collectionProp", name="HeaderManager.headers")
    for hk, hv in [("Content-Type", "application/json"), ("Accept", "application/json")]:
        h_el = ET.SubElement(h_coll, "elementProp", name="", elementType="Header")
        ET.SubElement(h_el, "stringProp", name="Header.name").text = hk
        ET.SubElement(h_el, "stringProp", name="Header.value").text = hv
    ET.SubElement(tp_hash, "hashTree")

    # CSV Data Set Config
    csv_ds = ET.SubElement(tp_hash, "CSVDataSet", guiclass="TestBeanGUI", testclass="CSVDataSet", testname="khoa_users", enabled="true")
    ET.SubElement(csv_ds, "stringProp", name="delimiter").text = ","
    ET.SubElement(csv_ds, "stringProp", name="fileEncoding").text = "UTF-8"
    ET.SubElement(csv_ds, "stringProp", name="filename").text = f"${{__P(csvdir,)}}/{data_cfg.get('csv_file', 'khoa_users.csv')}"
    ET.SubElement(csv_ds, "boolProp", name="ignoreFirstLine").text = "true"
    ET.SubElement(csv_ds, "boolProp", name="quotedData").text = "true" if data_cfg.get("allow_quoted_data", True) else "false"
    ET.SubElement(csv_ds, "boolProp", name="recycle").text = "true" if data_cfg.get("recycle_on_eof", True) else "false"
    ET.SubElement(csv_ds, "stringProp", name="shareMode").text = "shareMode.all"
    ET.SubElement(csv_ds, "boolProp", name="stopThread").text = "false"
    ET.SubElement(csv_ds, "stringProp", name="variableNames").text = ""
    ET.SubElement(tp_hash, "hashTree")

    # Function to add samplers to a hash tree
    def add_samplers(parent_hash):
        for req in workflow:
            label = req.get("label", "Request")
            method = req.get("method", "GET")
            path = req.get("path", "/")
            body = req.get("body", None)
            headers_dict = req.get("headers", {})
            extracts = req.get("extract", [])
            assertions = req.get("assertions", [])
            timer = req.get("think_time_ms", {})

            sampler = ET.SubElement(parent_hash, "HTTPSamplerProxy", guiclass="HttpTestSampleGui", testclass="HTTPSamplerProxy", testname=label, enabled="true")
            if body:
                ET.SubElement(sampler, "boolProp", name="HTTPSampler.postBodyRaw").text = "true"
                args_el = ET.SubElement(sampler, "elementProp", name="HTTPsampler.Arguments", elementType="Arguments")
                args_coll = ET.SubElement(args_el, "collectionProp", name="Arguments.arguments")
                arg_e = ET.SubElement(args_coll, "elementProp", name="", elementType="HTTPArgument")
                ET.SubElement(arg_e, "boolProp", name="HTTPArgument.always_encode").text = "false"
                ET.SubElement(arg_e, "stringProp", name="Argument.value").text = body
                ET.SubElement(arg_e, "stringProp", name="Argument.metadata").text = "="
            else:
                ET.SubElement(sampler, "boolProp", name="HTTPSampler.postBodyRaw").text = "false"

            ET.SubElement(sampler, "stringProp", name="HTTPSampler.path").text = path
            ET.SubElement(sampler, "stringProp", name="HTTPSampler.method").text = method
            ET.SubElement(sampler, "boolProp", name="HTTPSampler.follow_redirects").text = "true"
            ET.SubElement(sampler, "boolProp", name="HTTPSampler.use_keepalive").text = "true"

            s_hash = ET.SubElement(parent_hash, "hashTree")

            # Sampler specific headers
            if headers_dict:
                sm_hdr = ET.SubElement(s_hash, "HeaderManager", guiclass="HeaderPanel", testclass="HeaderManager", testname="Auth_Header", enabled="true")
                sm_coll = ET.SubElement(sm_hdr, "collectionProp", name="HeaderManager.headers")
                for sk, sv in headers_dict.items():
                    se = ET.SubElement(sm_coll, "elementProp", name="", elementType="Header")
                    ET.SubElement(se, "stringProp", name="Header.name").text = sk
                    ET.SubElement(se, "stringProp", name="Header.value").text = sv
                ET.SubElement(s_hash, "hashTree")

            # Extractors
            for ext in extracts:
                var_name = ext.get("var", "var")
                jp = ext.get("jsonpath", "$")
                m_no = str(ext.get("match_no", 1))
                d_val = ext.get("default", "")
                jext = ET.SubElement(s_hash, "JSONPostProcessor", guiclass="JSONPostProcessorGui", testclass="JSONPostProcessor", testname=f"extract_{var_name}", enabled="true")
                ET.SubElement(jext, "stringProp", name="JSONPostProcessor.referenceNames").text = var_name
                ET.SubElement(jext, "stringProp", name="JSONPostProcessor.jsonPathExprs").text = jp
                ET.SubElement(jext, "stringProp", name="JSONPostProcessor.match_numbers").text = m_no
                ET.SubElement(jext, "stringProp", name="JSONPostProcessor.defaultValues").text = d_val
                ET.SubElement(s_hash, "hashTree")

            # Assertions
            for ass in assertions:
                a_type = ass.get("type", "response_code")
                a_val = ass.get("value", "200")
                if a_type == "response_code":
                    ra = ET.SubElement(s_hash, "ResponseAssertion", guiclass="AssertionGui", testclass="ResponseAssertion", testname=f"assert_{label}_200", enabled="true")
                    c_prop = ET.SubElement(ra, "collectionProp", name="Asserion.test_strings")
                    ET.SubElement(c_prop, "stringProp", name="49586").text = a_val
                    ET.SubElement(ra, "stringProp", name="Assertion.test_field").text = "Assertion.response_code"
                    ET.SubElement(ra, "intProp", name="Assertion.test_type").text = "8"
                    ET.SubElement(s_hash, "hashTree")
                elif a_type == "jsonpath_exists":
                    ja = ET.SubElement(s_hash, "JSONPathAssertion", guiclass="JSONPathAssertionGui", testclass="JSONPathAssertion", testname="assert_json_path", enabled="true")
                    ET.SubElement(ja, "stringProp", name="JSON_PATH").text = a_val
                    ET.SubElement(ja, "boolProp", name="JSONVALIDATION").text = "false"
                    ET.SubElement(ja, "boolProp", name="EXPECT_NULL").text = "false"
                    ET.SubElement(s_hash, "hashTree")
                elif a_type == "regex_matches":
                    ra = ET.SubElement(s_hash, "ResponseAssertion", guiclass="AssertionGui", testclass="ResponseAssertion", testname="assert_regex", enabled="true")
                    c_prop = ET.SubElement(ra, "collectionProp", name="Asserion.test_strings")
                    ET.SubElement(c_prop, "stringProp", name="regex_val").text = a_val
                    ET.SubElement(ra, "stringProp", name="Assertion.test_field").text = "Assertion.response_data"
                    ET.SubElement(ra, "intProp", name="Assertion.test_type").text = "1"
                    ET.SubElement(s_hash, "hashTree")
                elif a_type == "response_contains":
                    ra = ET.SubElement(s_hash, "ResponseAssertion", guiclass="AssertionGui", testclass="ResponseAssertion", testname="assert_contains", enabled="true")
                    c_prop = ET.SubElement(ra, "collectionProp", name="Asserion.test_strings")
                    ET.SubElement(c_prop, "stringProp", name="contains_val").text = a_val
                    ET.SubElement(ra, "stringProp", name="Assertion.test_field").text = "Assertion.response_data"
                    ET.SubElement(ra, "intProp", name="Assertion.test_type").text = "2"
                    ET.SubElement(s_hash, "hashTree")

            # Timer
            if timer and timer.get("base", 0) > 0:
                urt = ET.SubElement(s_hash, "UniformRandomTimer", guiclass="UniformRandomTimerGui", testclass="UniformRandomTimer", testname="Timer", enabled="true")
                ET.SubElement(urt, "stringProp", name="ConstantTimer.delay").text = str(timer.get("base", 1000))
                ET.SubElement(urt, "stringProp", name="RandomTimer.range").text = str(timer.get("random", 1000))
                ET.SubElement(s_hash, "hashTree")

    # Build Thread Groups based on scenario
    if scenario_clean == "Stress" and "steps" in profile:
        # Fragment + Module Controllers
        frag = ET.SubElement(tp_hash, "TestFragmentController", guiclass="TestFragmentControllerGui", testclass="TestFragmentController", testname="FRAG_BrowseToBuy", enabled="false")
        frag_hash = ET.SubElement(tp_hash, "hashTree")
        add_samplers(frag_hash)

        for s_idx, step in enumerate(profile["steps"], 1):
            tg = ET.SubElement(tp_hash, "ThreadGroup", guiclass="ThreadGroupGui", testclass="ThreadGroup", testname=f"TG_Stress_Step{s_idx}_{step['threads']}VU", enabled="true")
            ET.SubElement(tg, "stringProp", name="ThreadGroup.on_sample_error").text = "continue"
            lc = ET.SubElement(tg, "elementProp", name="ThreadGroup.main_controller", elementType="LoopController", guiclass="LoopControlPanel", testclass="LoopController", testname="Loop Controller", enabled="true")
            ET.SubElement(lc, "boolProp", name="LoopController.continue_forever").text = "false"
            ET.SubElement(lc, "intProp", name="LoopController.loops").text = "-1"
            ET.SubElement(tg, "stringProp", name="ThreadGroup.num_threads").text = str(step["threads"])
            ET.SubElement(tg, "stringProp", name="ThreadGroup.ramp_time").text = str(step["ramp_up"])
            ET.SubElement(tg, "boolProp", name="ThreadGroup.scheduler").text = "true"
            ET.SubElement(tg, "stringProp", name="ThreadGroup.duration").text = str(step["duration"])
            ET.SubElement(tg, "stringProp", name="ThreadGroup.delay").text = str(step["delay"])
            ET.SubElement(tg, "boolProp", name="ThreadGroup.same_user_on_next_iteration").text = "true"
            
            tg_hash = ET.SubElement(tp_hash, "hashTree")
            mc = ET.SubElement(tg_hash, "ModuleController", guiclass="ModuleControllerGui", testclass="ModuleController", testname=f"MC_BrowseToBuy_{s_idx}", enabled="true")
            np = ET.SubElement(mc, "collectionProp", name="ModuleController.node_path")
            ET.SubElement(np, "stringProp", name="1").text = "Test Plan"
            ET.SubElement(np, "stringProp", name="2").text = testplan_name
            ET.SubElement(np, "stringProp", name="3").text = "FRAG_BrowseToBuy"
            ET.SubElement(tg_hash, "hashTree")

    elif scenario_clean == "Spike" and "spikes" in profile:
        frag = ET.SubElement(tp_hash, "TestFragmentController", guiclass="TestFragmentControllerGui", testclass="TestFragmentController", testname="FRAG_BrowseToBuy", enabled="false")
        frag_hash = ET.SubElement(tp_hash, "hashTree")
        add_samplers(frag_hash)

        # Baseline
        base_cfg = profile.get("baseline", {"threads": 10, "ramp_up": 30, "delay": 0, "duration": 360})
        tg0 = ET.SubElement(tp_hash, "ThreadGroup", guiclass="ThreadGroupGui", testclass="ThreadGroup", testname=f"TG_Spike_Baseline_{base_cfg['threads']}VU", enabled="true")
        ET.SubElement(tg0, "stringProp", name="ThreadGroup.on_sample_error").text = "continue"
        lc0 = ET.SubElement(tg0, "elementProp", name="ThreadGroup.main_controller", elementType="LoopController", guiclass="LoopControlPanel", testclass="LoopController", testname="Loop Controller", enabled="true")
        ET.SubElement(lc0, "intProp", name="LoopController.loops").text = "-1"
        ET.SubElement(tg0, "stringProp", name="ThreadGroup.num_threads").text = str(base_cfg["threads"])
        ET.SubElement(tg0, "stringProp", name="ThreadGroup.ramp_time").text = str(base_cfg["ramp_up"])
        ET.SubElement(tg0, "boolProp", name="ThreadGroup.scheduler").text = "true"
        ET.SubElement(tg0, "stringProp", name="ThreadGroup.duration").text = str(base_cfg["duration"])
        ET.SubElement(tg0, "stringProp", name="ThreadGroup.delay").text = str(base_cfg["delay"])
        
        tg0_hash = ET.SubElement(tp_hash, "hashTree")
        mc0 = ET.SubElement(tg0_hash, "ModuleController", guiclass="ModuleControllerGui", testclass="ModuleController", testname="MC_BrowseToBuy_Baseline", enabled="true")
        np0 = ET.SubElement(mc0, "collectionProp", name="ModuleController.node_path")
        ET.SubElement(np0, "stringProp", name="1").text = "Test Plan"
        ET.SubElement(np0, "stringProp", name="2").text = testplan_name
        ET.SubElement(np0, "stringProp", name="3").text = "FRAG_BrowseToBuy"
        ET.SubElement(tg0_hash, "hashTree")

        # Spikes
        for sp_idx, sp in enumerate(profile["spikes"], 1):
            tgs = ET.SubElement(tp_hash, "ThreadGroup", guiclass="ThreadGroupGui", testclass="ThreadGroup", testname=f"TG_Spike_Burst{sp_idx}_{sp['threads']}VU", enabled="true")
            ET.SubElement(tgs, "stringProp", name="ThreadGroup.on_sample_error").text = "continue"
            lcs = ET.SubElement(tgs, "elementProp", name="ThreadGroup.main_controller", elementType="LoopController", guiclass="LoopControlPanel", testclass="LoopController", testname="Loop Controller", enabled="true")
            ET.SubElement(lcs, "intProp", name="LoopController.loops").text = "-1"
            ET.SubElement(tgs, "stringProp", name="ThreadGroup.num_threads").text = str(sp["threads"])
            ET.SubElement(tgs, "stringProp", name="ThreadGroup.ramp_time").text = str(sp["ramp_up"])
            ET.SubElement(tgs, "boolProp", name="ThreadGroup.scheduler").text = "true"
            ET.SubElement(tgs, "stringProp", name="ThreadGroup.duration").text = str(sp["duration"])
            ET.SubElement(tgs, "stringProp", name="ThreadGroup.delay").text = str(sp["delay"])
            
            tgs_hash = ET.SubElement(tp_hash, "hashTree")
            mcs = ET.SubElement(tgs_hash, "ModuleController", guiclass="ModuleControllerGui", testclass="ModuleController", testname=f"MC_BrowseToBuy_Burst{sp_idx}", enabled="true")
            nps = ET.SubElement(mcs, "collectionProp", name="ModuleController.node_path")
            ET.SubElement(nps, "stringProp", name="1").text = "Test Plan"
            ET.SubElement(nps, "stringProp", name="2").text = testplan_name
            ET.SubElement(nps, "stringProp", name="3").text = "FRAG_BrowseToBuy"
            ET.SubElement(tgs_hash, "hashTree")

    else:
        # Standard Single Thread Group (Load or Endurance)
        th_count = profile.get("threads", 50)
        ramp_sec = profile.get("ramp_up_sec", 60)
        dur_sec = profile.get("duration_sec", 300)
        
        tg = ET.SubElement(tp_hash, "ThreadGroup", guiclass="ThreadGroupGui", testclass="ThreadGroup", testname=f"TG_{scenario_clean}_{th_count}VU", enabled="true")
        ET.SubElement(tg, "stringProp", name="ThreadGroup.on_sample_error").text = "continue"
        lc = ET.SubElement(tg, "elementProp", name="ThreadGroup.main_controller", elementType="LoopController", guiclass="LoopControlPanel", testclass="LoopController", testname="Loop Controller", enabled="true")
        ET.SubElement(lc, "intProp", name="LoopController.loops").text = "-1"
        ET.SubElement(tg, "stringProp", name="ThreadGroup.num_threads").text = str(th_count)
        ET.SubElement(tg, "stringProp", name="ThreadGroup.ramp_time").text = str(ramp_sec)
        ET.SubElement(tg, "boolProp", name="ThreadGroup.scheduler").text = "true"
        ET.SubElement(tg, "stringProp", name="ThreadGroup.duration").text = str(dur_sec)
        ET.SubElement(tg, "stringProp", name="ThreadGroup.delay").text = "0"
        
        tg_hash = ET.SubElement(tp_hash, "hashTree")
        add_samplers(tg_hash)

    # Add Listener to Test Plan level
    if listener_type == "SummaryReport":
        ET.SubElement(tp_hash, "ResultCollector", guiclass="SummaryReport", testclass="ResultCollector", testname="Summary Report", enabled="true")
        ET.SubElement(tp_hash, "hashTree")
    elif "ViewResultsTree" in listener_type:
        vrt = ET.SubElement(tp_hash, "ResultCollector", guiclass="ViewResultsFullVisualizer", testclass="ResultCollector", testname="View Results Tree", enabled="true")
        ET.SubElement(vrt, "boolProp", name="ResultCollector.error_logging").text = "true"
        ET.SubElement(tp_hash, "hashTree")
    else:
        ET.SubElement(tp_hash, "ResultCollector", guiclass="StatVisualizer", testclass="ResultCollector", testname="Aggregate Report", enabled="true")
        ET.SubElement(tp_hash, "hashTree")

    # Pretty print XML
    xml_str = ET.tostring(root, encoding='utf-8')
    parsed = minidom.parseString(xml_str)
    pretty_xml = parsed.toprettyxml(indent="  ", encoding="utf-8").decode('utf-8')

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(pretty_xml)
    print(f"[generate_jmx] Successfully generated {out_path}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Generate JMeter XML Test Plan from JSON config")
    parser.add_argument('--config', required=True, help="Path to workflow JSON configuration")
    parser.add_argument('--scenario', default="Load", choices=["Load", "Stress", "Spike", "Endurance"], help="Scenario type")
    parser.add_argument('--out', '--output', dest='out', default=None, help="Output .jmx file path")
    args = parser.parse_args()

    build_jmx_from_config(args.config, args.scenario, args.out)
